# Generated by Django 4.2.4 on 2024-06-30 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
