# Generated by Django 4.2.4 on 2024-06-29 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="following",
            new_name="followings",
        ),
    ]
