# Generated by Django 4.2.4 on 2024-07-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_following_userprofile_followings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followings",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="profiles.userprofile"
            ),
        ),
    ]
