# Generated by Django 5.0.6 on 2024-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_userprofile_followings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="following",
                to="profiles.userprofile",
            ),
        ),
    ]
